### PR TITLE
Switched from node-fetch to http-call

### LINKED ISSUE #87: Fallback to IPv4 when making API calls
Currently there is no retry mechanism for making API calls. This means that if the request encounters some form of network error, the call will fail without any attempt to retry. Perhaps the most obvious instance of this is when the interface being used has an IPv6 address assigned, but the destination host is unreachable. This will result in an error such as this one
```
./bin/run login
 ›   Error: request to https://auth.apimetrics.io/oauth/device/code failed, reason: connect EHOSTUNREACH 2606:4700::6810:d8f1:443
```

The requests should at least make an attempt to fall back to IPv4 for requests when needed.

### LINKED ISSUE #107: DeprecationWarning: The `punycode` module is deprecated. Please use a userland alternative instead.
A depreciation warning exists when running any command that calls an API. This was tracked to the `whatwg-url` module which is a dependency of `node-fetch`. The dependency was removed in `v3.3.2` however this is an ESM module making upgrade complicated. However, this issue should be resolved by making the planned switch to `http-call` given in #87.

```
(node:15302) [DEP0040] DeprecationWarning: The `punycode` module is deprecated. Please use a userland alternative instead.
    at node:punycode:3:9
    at BuiltinModule.compileForInternalLoader (node:internal/bootstrap/realm:392:7)
    at BuiltinModule.compileForPublicLoader (node:internal/bootstrap/realm:328:10)
    at loadBuiltinModule (node:internal/modules/helpers:102:7)
    at Module._load (node:internal/modules/cjs/loader:995:17)
    at Module.require (node:internal/modules/cjs/loader:1229:19)
    at require (node:internal/modules/helpers:177:18)
    at Object.<anonymous> (/home/mnickson/source/APImetrics/APIm-CLI/node_modules/whatwg-url/lib/url-state-machine.js:2:18)
    at Module._compile (node:internal/modules/cjs/loader:1369:14)
    at Module._extensions..js (node:internal/modules/cjs/loader:1427:10)
```

### PR DESCRIPTION
**Pull request by Computroniks**
# Summary
Switched package used for calling the API from `node-fetch` to `http-call`.

Closes #87 
Closes #107 

### Type

- [ ] Feature
- [x] Bug Fix
- [ ] Breaking Change

# Technical Description
In order to fix #107 and #87, the package used to make API calls has been switched from node-fetch to http-call, a package developed by Heroku for their CLI that supports automatic retries and proxy handling.

The API class has been fully updated to make use of the new package. This did result in a slight change to the interface of the class with the plain flag being moved into the options type and the body now can be directly passed as an object instead of having to convert to a JSON string first. This however has not had much impact on the rest of the code and the minor change has been made where required.

Errors from API requests are now of the type HTTPError rather than ApiError (our own custom error that has now been removed). This provides more information about the error including the response body so the parts of code that dealt previously with ApiError have been updated for HTTPError and the old ApiError has been removed.

Whilst testing http-call for the Auth class, an unrelated bug was discovered in the pollToken method. The sleep call passed the time to sleep in seconds when milliseconds was expected, resulting in too many requests to the token endpoint and the resulting slow_down requests being ignored.

A further logic error with the pollToken method was discovered when handling the slow_down error. The intention was for the sleep delay to double each time the slow_down error was handled, however as implemented the original retry interval was just doubled, i.e. 5, 10, 10, ..., 10. this was fixed along side the millisecond issue.

# Self Review

- [x] I have commented my code where needed, including JSDoc / TSDoc
- [x] I have added / updated command tests
- [x] I have run `npm run test` and it generates no new errors or warnings
- [x] I have reviewed my code to ensure there are no artifacts left over from development
- [x] I have tested my code to ensure it functions as intended

### CODE REVIEW

File: src/base-command/api.ts [hunk 1]
```diff
@@ -1,22 +1,25 @@
...
 import {Auth} from './auth';
-import fetch, {RequestInit} from 'node-fetch';
+import {OutgoingHttpHeaders} from 'node:http';
+import HTTP from 'http-call';
 import {Config} from './config';
 import {debug} from 'debug';
-import {ApiError as TApiError, ListResponse, UserInfo} from './types';
-import {ApiError} from './errors';
+import {ListResponse, UserInfo} from './types';
+// import {ApiError} from './errors';
```
Comment (Computroniks) [inline src/base-command/api.ts:8]: Dev artefact
```suggestion
```

**Review by ndenny — APPROVED** [review]
I like we've removed a lot of JSON.stringify calls!
